name: paypal_sdk
description: PayPal SDK for facilitating integration with PayPal REST APIs
homepage: https://github.com/Omnimind-Ltd/paypal-sdk
version: 1.0.3

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  json_annotation: ^4.7.0
  http: ^0.13.5
  logging: ^1.1.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.6
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
