name: paypal_sdk
description: PayPal SDK for simplifying integration with PayPal REST APIs
homepage: https://github.com/Omnimind-Ltd/paypal-sdk
version: 0.4.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.1.0
  http: ^0.13.4
  logging: ^1.0.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.18.2
  build_runner: ^2.1.4
  json_serializable: ^5.0.2
