name: paypal_sdk
description: PayPal SDK
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.1.0
  http: ^0.13.3
  logging: ^1.0.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.12
  build_runner: ^2.1.2
  json_serializable: ^5.0.2
